-- MySQL Script generated by MySQL Workbench
-- Thứ hai, 25 Tháng sáu Năm 2018 15:03:44 +07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema node_TUT
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema node_TUT
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `node_TUT` DEFAULT CHARACTER SET utf8 ;
USE `node_TUT` ;

-- -----------------------------------------------------
-- Table `node_TUT`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `node_TUT`.`user` (
  `UserID` INT(11) NOT NULL,
  `UserName` VARCHAR(45) NOT NULL,
  `UserEmail` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`UserID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `node_TUT`.`device`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `node_TUT`.`device` (
  `DeviceID` INT(11) NOT NULL,
  `DeviceName` VARCHAR(45) NOT NULL,
  `UserID` INT(11) NOT NULL,
  PRIMARY KEY (`DeviceID`, `UserID`),
  INDEX `UserID_idx` (`UserID` ASC),
  CONSTRAINT `UserID`
    FOREIGN KEY (`UserID`)
    REFERENCES `node_TUT`.`user` (`UserID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
